mpiexec -n 2 knn.exe
mpiexec -n 3 knn.exe
mpiexec -n 4 knn.exe
mpiexec -n 5 knn.exe
mpiexec -n 6 knn.exe
mpiexec -n 7 knn.exe
mpiexec -n 8 knn.exe
mpiexec -n 9 knn.exe
mpiexec -n 10 knn.exe
mpiexec -n 11 knn.exe
mpiexec -n 12 knn.exe
mpiexec -n 13 knn.exe
mpiexec -n 14 knn.exe
mpiexec -n 15 knn.exe
mpiexec -n 16 knn.exe
mpiexec -n 17 knn.exe
mpiexec -n 18 knn.exe
mpiexec -n 19 knn.exe
mpiexec -n 20 knn.exe
mpiexec -n 21 knn.exe
mpiexec -n 22 knn.exe
mpiexec -n 23 knn.exe
mpiexec -n 24 knn.exe
mpiexec -n 25 knn.exe