mpiexec -n 1 py kmeans.py
mpiexec -n 2 py kmeans.py
mpiexec -n 3 py kmeans.py
mpiexec -n 4 py kmeans.py
mpiexec -n 5 py kmeans.py
mpiexec -n 6 py kmeans.py
mpiexec -n 7 py kmeans.py
mpiexec -n 8 py kmeans.py
mpiexec -n 9 py kmeans.py
mpiexec -n 10 py kmeans.py
mpiexec -n 11 py kmeans.py
mpiexec -n 12 py kmeans.py
mpiexec -n 13 py kmeans.py
mpiexec -n 14 py kmeans.py
mpiexec -n 15 py kmeans.py
mpiexec -n 16 py kmeans.py
mpiexec -n 17 py kmeans.py
mpiexec -n 18 py kmeans.py
mpiexec -n 19 py kmeans.py
mpiexec -n 20 py kmeans.py
mpiexec -n 21 py kmeans.py
mpiexec -n 22 py kmeans.py
mpiexec -n 23 py kmeans.py
mpiexec -n 24 py kmeans.py
mpiexec -n 25 py kmeans.py